{% set version = "0.70.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-powerlaw
  version: {{ version|replace("-", "_") }}

source:
  fn: poweRlaw_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/poweRlaw_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/poweRlaw/poweRlaw_{{ version }}.tar.gz
  sha256: 936f31588d7eb900d22db019c2c11361f580111b96c59d202d5f8dd46b82eaa7

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-vgam
  run:
    - r-base
    - r-vgam

test:
  commands:
    - $R -e "library('poweRlaw')"           # [not win]
    - "\"%R%\" -e \"library('poweRlaw')\""  # [win]

about:
  home: https://github.com/csgillespie/poweRlaw
  license: GPL-2 | GPL-3
  summary: An implementation of maximum likelihood estimators for a variety of heavy tailed distributions, including both the discrete and continuous power law distributions.
    Additionally, a goodness-of-fit based approach is used to estimate the lower cut-off for the scaling region.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
